import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import moocImg from '../common/assets/javascript.jpg'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>      
         
          <span className={styles.logo}>
            <Image src={moocImg} alt="Vercel Logo" width={72} height={16} />
          </span>
       
    </div>
  )
}
